In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer

In [3]:
loan=pd.read_csv(r"C:\Final project\Loan_data.csv")
loan

Cutomer id  Cards  Debit card  Insurance   Age  Cibil Score  Loan offer
0              5    0.0         1.0        0.0  50.0       34.940           0
1              3    1.0         0.0        0.0  18.0        0.891           1
2             66    0.0         1.0        0.0   5.0        0.330           1
3             70    0.0         1.0        1.0  31.0        0.037           0
4             96    0.0         1.0        0.0  30.0        0.038           1
...          ...    ...         ...        ...   ...          ...         ...
1335       34100    0.0         1.0        0.0   NaN        0.576           1
1336       34110    1.0         1.0        0.0  46.0        3.705           0
1337       34113    1.0         1.0        0.0  39.0        0.099           1
1338       34145    1.0         0.0        0.0   8.0        3.177           0
1339       34153    1.0         1.0        0.0  30.0        0.688           1

[1340 rows x 7 columns]

In [4]:
loan.head()

Cutomer id  Cards  Debit card  Insurance   Age  Cibil Score  Loan offer
0           5    0.0         1.0        0.0  50.0       34.940           0
1           3    1.0         0.0        0.0  18.0        0.891           1
2          66    0.0         1.0        0.0   5.0        0.330           1
3          70    0.0         1.0        1.0  31.0        0.037           0
4          96    0.0         1.0        0.0  30.0        0.038           1

In [5]:
loan.isnull().sum()

Cutomer id       0
Cards           12
Debit card      41
Insurance       48
Age            189
Cibil Score      0
Loan offer       0
dtype: int64

In [14]:
loan["Cards"].unique()

array([ 0.,  1., nan])

In [16]:
loan["Debit card"].unique()

array([ 1.,  0., nan])

In [17]:
loan["Insurance"].unique()

array([ 0.,  1., nan])

In [28]:
# Fill missing values in 'Age' column with the mean value
loan['Age'].fillna(loan['Age'].mean(), inplace=True)

In [29]:
loan.isnull().sum()

Cutomer id      0
Cards          12
Debit card     41
Insurance      48
Age             0
Cibil Score     0
Loan offer      0
dtype: int64

In [31]:
# Separate features and target variable
X = loan[['Cards', 'Debit card', 'Insurance', 'Age', 'Cibil Score']]
y = loan['Loan offer']

In [33]:
# Fill missing values in 'Cards', 'Debit card', and 'Insurance' columns with the most frequent value
imputer = SimpleImputer(strategy='most_frequent')
X[['Cards', 'Debit card', 'Insurance']] = imputer.fit_transform(X[['Cards', 'Debit card', 'Insurance']])

C:\Users\buffi\AppData\Local\Temp\ipykernel_25344\1388537618.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['Cards', 'Debit card', 'Insurance']] = imputer.fit_transform(X[['Cards', 'Debit card', 'Insurance']])


In [36]:
X.isnull().sum()

Cards          0
Debit card     0
Insurance      0
Age            0
Cibil Score    0
dtype: int64

In [37]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
# Create and train the model
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [66]:
# Make predictions on the test set
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy:", accuracy*100)

Accuracy: 67.53731343283582
